// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTunnel(arg1:main.TunnelConfig):Promise<main.TunnelConfig>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function GetStatuses():Promise<Array<main.TunnelStatus>>;

export function GetTunnels():Promise<Array<main.TunnelConfig>>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function UpdateTunnel(arg1:main.TunnelConfig):Promise<void>;
