// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatuses() {
  return window['go']['main']['App']['GetStatuses']();
}

export function GetTunnels() {
  return window['go']['main']['App']['GetTunnels']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function UpdateTunnel(arg1) {
  return window['go']['main']['App']['UpdateTunnel'](arg1);
}
